import { cormorant, inter } from "@/ui/fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${cormorant.variable}  h-full antialiased border-border outline-ring/50`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground font-body">
        {children}</body>
    </html>
  );
}
